name: accounting
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10000

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.1.0
  provider: ^6.0.3
  table_calendar: ^3.0.7
  syncfusion_flutter_charts: ^20.2.49
  syncfusion_flutter_datepicker: ^20.2.49
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  sqflite: ^2.1.0
  flutter_colorpicker: ^1.0.3
  dropdown_textfield: ^1.0.4
  dropdown_button2: ^1.8.2
  fluttertoast: ^8.0.8
  numberpicker: ^2.1.1
  flutter_multi_select_items: ^0.4.2
  flutter_local_notifications: ^9.3.2
  flutter_native_timezone: ^2.0.0
  excel: ^2.0.0-null-safety-3
  path: ^1.8.2
  path_provider: ^2.0.11
  share_plus: ^4.5.3
  google_mobile_ads: ^2.1.0
  flutter_email_sender: ^5.0.2
  in_app_purchase: ^3.0.8
  in_app_purchase_android: ^0.2.3+6
  url_launcher: ^6.1.6
  package_info_plus: ^1.0.1
  flutter_localizations:
    sdk: flutter

  #google drive
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  google_sign_in: ^5.4.2

#firebase
  firebase_core: ^2.1.0
  firebase_analytics: ^10.0.2
  firebase_auth: ^4.0.2
  firebase_remote_config: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-VariableFont_wght.ttf
        - asset: fonts/Raleway-Italic-VariableFont_wght.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-VariableFont_wght.ttf
        - asset: fonts/RobotoMono-Italic-VariableFont_wght.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
